### ISSUE TITLE
Tag density fails on large tag counts

### ISSUE THREAD

**Issue by ZeLonewolf** [ZeLonewolf/osm-overpass-scripts#2]
For large tag counts (in the millions, for example, `building=yes`), the overpass query will silently fail.

What's needed is to:
1. Query taginfo to figure out how big the tag count is
2. If it's "too big" divide the world into chunks and make a series of subsequent OP queries, and stitch the results together.

**Comment by Mashin6** [comment]
I was thinking how to get the count, because OP query like
```
[out:json];
nw["building"];
out count;
```
just runs out of memory.

But we can get the count estimate from taginfo itself via API
`https://taginfo.openstreetmap.org/api/4/tag/stats?key=building&value=yes`

**Comment by Mashin6** [comment]
Is now fixed with iterative splitting of bbox areas.

**Comment by ZeLonewolf** [comment]
Great work on solving this!
