### ISSUE TITLE
Rplots.pdf always empty

### ISSUE THREAD

**Issue by petermisovic** [ZeLonewolf/osm-overpass-scripts#3]
Rplots.pdf is always empty when scripts processing is done.

**Comment by Mashin6** [comment]
Switched to different plotting function that doesn't have that issue. 87470faa4a44229d1b72d19588879c85c9bc9124

**Comment by petermisovic** [comment]
Downloaded the code again, run ./get_tag_density_map.sh script, but no pdf has been created. Could it be related to package: tidyverse? I see:
![Screenshot from 2021-05-26 22-29-56](https://user-images.githubusercontent.com/11147552/119726914-f53e1300-be71-11eb-9b18-364e1d2c78e5.png)

**Comment by Mashin6** [comment]
you have to specify it in the name e.g. `--map myFile.pdf`

In theory these should be supported "eps", "ps", "tex" (pictex), "pdf", "jpeg", "tiff", "png", "bmp", "svg" or "wmf" (windows only), but it is untested.

**Comment by petermisovic** [comment]
OK, I used it like --map myFile.png and Rplots.pdf has been automatically created. Tested, pdf successfully created with content. Thanks!
