### ISSUE TITLE
Rename `*.op` files to `*.overpassql`

### ISSUE THREAD

**Issue by 1ec5** [ZeLonewolf/osm-overpass-scripts#5]
@FloEdelmann is opening a bunch of issues in various repositories to [standardize on the .overpassql extension](https://wiki.openstreetmap.org/wiki/Overpass_API/Overpass_QL#File_extension) for files containing OverpassQL queries, in order to achieve a critical mass of repositories for OverpassQL syntax highlighting on GitHub: github/linguist#5890. Perhaps the four files in the queries folder could be renamed?

**Comment by ZeLonewolf** [comment]
Code that uses them would also have to be renamed, not just the query files themselves.

**Comment by Mashin6** [comment]
Names of query files were changed in [16f5340](https://github.com/ZeLonewolf/osm-overpass-scripts/commit/16f534016afabde8e1a488d173aa80ef6b1aadee)

**Comment by FloEdelmann** [comment]
Thanks for renaming!
